#cmake -DCMAKE_INSTALL_PREFIX=/home/mark/src/usr -DCMAKE_C_FLAGS="-fPIC ${BSON_EXTRA_CFLAGS}" -DCMAKE_BUILD_TYPE=Debug -DENABLE_STATIC=ON ..
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/home/mark/src/usr -DCMAKE_C_FLAGS="-fPIC ${BSON_EXTRA_CFLAGS}" -DCMAKE_BUILD_TYPE=Debug -DENABLE_STATIC=ON ..

